const GET_USER = 'GET_USER';
const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
const GET_USER_ERROR = 'GET_USER_ERROR';

const LOGIN_USER = 'LOGIN_USER';
const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

const LOGOUT_USER = 'LOGOUT_USER';
const LOGOUT_USER_FULFILLED = 'LOGOUT_USER_FULFILLED';
const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export default {
    GET_USER,
    GET_USER_FULFILLED,
    GET_USER_ERROR,
    LOGIN_USER,
    LOGIN_USER_FULFILLED,
    LOGIN_USER_ERROR,
    LOGOUT_USER,
    LOGOUT_USER_FULFILLED,
    LOGOUT_USER_ERROR
};
