const GET_SPECIFICATIONS = 'CAR_GET_SPECIFICATIONS';
const GET_SPECIFICATIONS_FULFILLED = 'CAR_GET_SPECIFICATIONS_FULFILLED';
const GET_SPECIFICATIONS_ERROR = 'CAR_GET_SPECIFICATIONS_ERROR';

const ADD_QUOTE = 'CAR_ADD_QUOTE';
const ADD_QUOTE_FULFILLED = 'CAR_ADD_QUOTE_FULFILLED';
const ADD_QUOTE_ERROR = 'CAR_ADD_QUOTE_ERROR';

export default {
    GET_SPECIFICATIONS,
    GET_SPECIFICATIONS_FULFILLED,
    GET_SPECIFICATIONS_ERROR,
    ADD_QUOTE,
    ADD_QUOTE_FULFILLED,
    ADD_QUOTE_ERROR
};
